### ISSUE TITLE
Fix Command Injection vulnerability in v2

### ISSUE THREAD

**Issue by matias-la** [rosen-vladimirov/global-modules-path#18]
The [command injection advisory regarding this package](https://github.com/advisories/GHSA-vvj3-85vf-fgmw) indicates that all versions prior to `3.0.0` are vulnerable. According to the download stats in https://www.npmjs.com/package/global-modules-path?activeTab=versions, the non-vulnerable version has almost no downloads compared to the vulnerable ones. This is caused because most projects use version markers such as `^2.1.0`, that won't upgrade to v3 by default.

Would it be possible to release a patch version, such as 2.3.2, that only fixes the vulnerability while leaving out all the changes from v3? This way, it would be trivial for the users of the package to upgrade, and they wouldn't need to worry about backwards-incompatible changes. Releasing patch versions that fix vulnerabilities is considered a best practice in package maintenance.

**Comment by rosen-vladimirov** [comment]
Hey @matias-la , 
When I was about to publish the new version, I was wondering which version to choose - 3.0 or 2.3.2. However, as the fix required a full change of the methods for spawning the processes, I was not sure I'm not actually introducing a breaking change in the behavior. I mean - something that was working yesterday to stop working today. I've tried to cover everything with tests, but still I did not want to break existing packages, so I've gone with 3.0 version.
So, just to be on the safe side, I prefer to keep the fix in version 3.0.
